language: ruby
sudo: true
dist: trusty
rvm:
- 2.4
- jruby
branches:
  only:
  - source
env:
  global:
  - JEKYLL_ENV=production
script:
  - gem install bundler
  - bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  local_dir: _site
  on:
    branch: source
